name: Bug report
description: Tell us when bunWay misbehaves so we can fix it fast.
title: "bug: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us make bunWay better! Please share as much context as you can.
  - type: textarea
    id: summary
    attributes:
      label: What happened?
      description: A clear, concise description of the problem.
      placeholder: Describe the unexpected behaviour.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Include code samples, routes, or tests that expose the issue.
      placeholder: |
        1. …
        2. …
        3. …
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      placeholder: The behaviour you expected to see.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Bun version, bunWay version, OS, and any other relevant details.
      placeholder: |
        - bunWay: v0.x.x
        - Bun: v1.2.x
        - OS: macOS/Linux/Windows
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs and diagnostics
      description: Paste any stack traces or test output that might help.
      render: shell
  - type: dropdown
    id: regression
    attributes:
      label: Did this work in a previous version?
      options:
        - "Unsure"
        - "It used to work"
        - "First time trying"
    validations:
      required: true
  - type: textarea
    id: extra
    attributes:
      label: Anything else?
      description: Links to related issues, PRs, or context that might help.
